### PR TITLE
.travis.yml: Change name and email to defaults

### PR DESCRIPTION
**Pull request by bhavya17037**
Change name and emails to defaults and use keep-history as the
generated commits are not extra work being done by anyone

Closes https://github.com/coala/git-task-list/issues/48

### CODE REVIEW

**Comment by bhavya17037** [comment]
@RaiVaibhav yes I have added keep-history and have set it to true

**Comment by RaiVaibhav** [comment]
Nvm

**Comment by bhavya17037** [comment]
So will the maintainer approve this?

**Comment by RaiVaibhav** [comment]
Yeah why wouldn't they :sweat_smile:

**Comment by jayvdb** [comment]
The defaults could have been omitted, but it doesnt hurt to list them.

**Pull request merged**
